#需要设置spring.profiles.active=dev选择环境加载配置文件。
#这里不考虑配置中心,比如naocs 阿波罗 consul
spring:
  application:
    name: dyy-gateway-dispatcher
  kafka:
    bootstrapServers: localhost:9092
    consumers:
      dispatcher:
        topic: dyy_dispatcher_data
        groupId: ${spring.application.name}
        listener: com.dyy.tsp.gateway.dispatcher.kafka.DispatcherListener
        valueDeserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      valueSerializer: org.apache.kafka.common.serialization.StringSerializer
  redis:
    host: localhost
    port: 6379
    password: 123456
    jedis:
      maxActive: 20
      maxWait: -1
      maxIdle: 8
      onBorrow: true
    database:
      vehicle: 0
      location: 1
      transient: 2
      command: 3

tcu:
  kafkaAcks: 1
  kafkaLinger: 50
  kafkaRetries: 1
  kafkaRetryBackoff: 2000
  kafkaReconnectBackoff: 3000
  kafkaCompressionType: gzip
  statusTopic: dyy_status_data
  faultTopic: dyy_fault_data
  warningTopic: dyy_warning_data
  locationTopic: dyy_location_data

logging:
  level:
    com.dyy.tsp: DEBUG

server:
  port: 9003
  tomcat:
    accesslog:
      enabled: false
      directory: logs
      pattern: common
      prefix: access_log